### PR TITLE
Add support for PHP 8.1

### PR DESCRIPTION
**Pull request by arueckauer**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

PHP 8.1 support.

### CODE REVIEW

**Comment by froschdesign** [comment]
```
Fatal error: During inheritance of IteratorAggregate: Uncaught Return type of org\bovigo\vfs\vfsStreamDirectory::getIterator() should either be compatible with IteratorAggregate::getIterator(): 

Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
/github/workspace/vendor/mikey179/vfsstream/src/main/php/org/bovigo/vfs/vfsStreamDirectory.php:248
```
Looks like a newer version of `mikey179/vfsstream` is needed: https://github.com/bovigo/vfsStream/releases/tag/v1.6.10

**Comment by froschdesign** [comment]
19 errors:
```
MezzioTest\Tooling\CreateHandler\CreateActionCommandTest::testSuccessfulExecutionEmitsExpectedMessagesWhenRequestingAnAction

PHPUnit\Framework\Exception: PHP Deprecated:

Return type of Symfony\Component\Console\Helper\HelperSet::getIterator()
should either be compatible with IteratorAggregate::getIterator():
Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /github/workspace/vendor/symfony/console/Helper/HelperSet.php on line 104
```
The [problem is already fixed](https://github.com/symfony/symfony/pull/42260) but not yet released: https://github.com/symfony/symfony/milestone/22

**Comment by arueckauer** [comment]
Tests are failing due to deprecation notices in installed version of `symfony/console`. `laminas/laminas-cli` and `malukenho/docheader` require `symfony/console`. While `laminas/laminas-cli` adds a newer version of `symfony/console` as well as PHP 8.1 support in version `1.2`, `malukenho/docheader` provides neither.

I was not able to find any usages of `malukenho/docheader`. Is it safe to drop it?

**Comment by froschdesign** [comment]
@arueckauer 
> Is it safe to drop it?

All file headers (DocBlocks) are removed, so we can drop `malukenho/docheader`! 👍

**Review by froschdesign — APPROVED** [review]

**Comment by froschdesign** [comment]
@arueckauer 
Thank you for your time and this contribution! ❤️

**Pull request merged**
