### PR TITLE
Add support for PHP 8.4

### PR DESCRIPTION
**Pull request by gsteel**
- Bump dev deps
- Add BC Checker to CI
- Ignore platform reqs
- Fix a number of minor SA issues

### CODE REVIEW

**Comment by gsteel** [comment]
Need to determine minimum version of symfony console to conflict with, or we need to bump laminas-cli to a 8.4 compatible release

**Comment by fezfez** [comment]
@gsteel see https://github.com/laminas/laminas-cli/pull/131

**Comment by gsteel** [comment]
This can't happen until #58 has been resolved anyhow

**Comment by gsteel** [comment]
Handled in #59

**Pull request closed without merging**
