### PR TITLE
Add support for PHP 8.4

### PR DESCRIPTION
**Pull request by weierophinney**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

This patch adds support for PHP 8.4.

To accomplish this, it also bumps PHPUnit to 10.5. Doing so uncovered a previously undetected issue with the RoutesFilter, whereby a class name used as filter was not properly escaped, causing the regexp to fail compilation; this has been fixed now.

### CODE REVIEW

**Comment by gsteel** [comment]
Conflicting with amphp/amp < 2.6.4 solves these deprecations I think.

Release is blocked here until #58 is resolved because #52 was merged without proper review.

**Comment by froschdesign** [comment]
> Conflicting with amphp/amp < 2.6.4 solves these deprecations I think.

Should be true, because we already had this problem in other components.

**Comment by weierophinney** [comment]
@gsteel All dependency issues resolved — there were some issues with older symfony components as well.

**Comment by weierophinney** [comment]
Should these be merged, and #58 rebased, or would it be better to rebase this after that one is merged?

**Review by gsteel — APPROVED** [review]
LGTM! 👍

**Comment by gsteel** [comment]
Merged as-is #58 has a way to go, so the rebase can happen there 👍

**Comment by samsonasik** [comment]
let's create 2.10.0 release for it so it can be consumed on mezzio-skeleton

https://github.com/mezzio/mezzio-skeleton/actions/runs/13651123224/job/38159717402?pr=163#step:3:76

**Comment by samsonasik** [comment]
Released mezzio-tooling 2.10.0 https://github.com/mezzio/mezzio-tooling/releases/tag/2.10.0

**Comment by gsteel** [comment]
> Released mezzio-tooling 2.10.0 https://github.com/mezzio/mezzio-tooling/releases/tag/2.10.0

😱 @samsonasik - 2.10.x contained merged PRs that were committed without sufficient review: #52 should never have got merged, and the unmerged patch #58 was supposed to rectify the problems before release.

It's probably my fault for not somehow blocking the release - Not sure what to do now because what was merged in #52 can't be fixed without BC breaks.

Questions:
- is there a procedure I'm unaware of for preventing releases from going out in this sort of situation?
- what do we do now?

cc @mezzio/technical-steering-committee

**Comment by samsonasik** [comment]
@gsteel I see, there is no milestone on #58 so I missed that. IMO, next minor release will be fine for #58 since new class was final, so likely less BC break :)

**Comment by froschdesign** [comment]
> …since new class was final…

https://github.com/mezzio/mezzio-tooling/blob/375ea79ded5816f55147dacc785d5625a898cc5d/src/Routes/ListRoutesCommand.php#L26

**Comment by gsteel** [comment]
There's loads of stuff in that patch that needs rectifying, interfaces and public members included

**Comment by samsonasik** [comment]
@froschdesign ah, I see, @gsteel new patch release probably needed without introducing another API method /cc @settermjd

**Pull request merged**
