### PR TITLE
Allow `symfony/process:^6`

### PR DESCRIPTION
**Pull request by snapshotpl**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

Allow symfony/process v6

### CODE REVIEW

**Comment by Ocramius** [comment]
Looks like this is failing due to latest `composer/composer`? :thinking:

**Comment by snapshotpl** [comment]
No idea. Locally updated to newest composer and running on PHP 7.4.3 pass in 100%.

**Comment by Ocramius** [comment]
Yeah, potentially fixed by https://github.com/composer/composer/releases/tag/2.2.3

I wonder if we should upgrade our CI images regularly :thinking:

**Comment by boesing** [comment]
> I wonder if we should upgrade our CI images regularly 🤔

We've already talked about that regarding new PHP versions. 
PHP is released on a monthly based, so we could schedule for monthly builds.
But this won't help us in this specific case, so we would end-up having manual builds for these cases where composer has released bugfixes we do need.

**Comment by Ocramius** [comment]
@boesing if we use `COPY --from=composer:2.2.3`, for example, then @dependabot could potentially pick up on that, and upgrade it regularly. 

In this case, I really believe the bug is either with `composer/composer` or `phpunit/phpunit`

**Comment by snapshotpl** [comment]
How to update composer here?

**Comment by Ocramius** [comment]
Not here: needs to happen in https://github.com/laminas/laminas-continuous-integration-action

**Comment by boesing** [comment]
> @boesing if we use `COPY --from=composer:2.2.3`, for example, then @dependabot could potentially pick up on that, and upgrade it regularly.

Really? dependabot is able to bump dockerfile? That would be awesome!

**Comment by Ocramius** [comment]
It does: using it regularly on customer projects that are docker-heavy 💪

**Comment by Ocramius** [comment]
Looks like some adjustments are needed for static analysis, but otherwise really promising 💪

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Thanks @snapshotpl!

**Comment by snapshotpl** [comment]
Wait a minute, fixing some psalm issues now

**Comment by Ocramius** [comment]
Too late :|

**Comment by Ocramius** [comment]
Send me another patch, I'll factor it in the release 👍

**Pull request merged**
